version: "3.8"

services:
  bienesraices:
    image: mysql:8.2.0
    container_name: "bienesraices"
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    ports:
      - '3306:3307'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080