version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: bienesraices
    volumes:
      - .:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3001:3001
    volumes:
      - .:/app
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
